// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIM6PLyT1K_vgM38r206wrQ4LHXWqoiLY',
    appId: '1:313098152142:web:8b2091fd85dc91d499889f',
    messagingSenderId: '313098152142',
    projectId: 'chat-app-e6b3b',
    authDomain: 'chat-app-e6b3b.firebaseapp.com',
    storageBucket: 'chat-app-e6b3b.appspot.com',
    measurementId: 'G-CJZK4RY3N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZg2gDif5HmN8MlErkcmybaK3-xOKG2Zg',
    appId: '1:313098152142:android:f430336c12431fb099889f',
    messagingSenderId: '313098152142',
    projectId: 'chat-app-e6b3b',
    storageBucket: 'chat-app-e6b3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjoOlOkK1HEm4qWPoWL6y-THAKxCo1Viw',
    appId: '1:313098152142:ios:3c70202520bf43eb99889f',
    messagingSenderId: '313098152142',
    projectId: 'chat-app-e6b3b',
    storageBucket: 'chat-app-e6b3b.appspot.com',
    iosClientId: '313098152142-lu2ics37n6iiu03vv1dk2l6troh18ds7.apps.googleusercontent.com',
    iosBundleId: 'com.example.goChat',
  );
}
